version: '3.8'

services:
  model_evaluation_platform_frontend:
    platform: linux/amd64
    command: yarn run start
    build:
      context: ./web-app
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_EVALUATE_URL=http://gan.cs.cityu.edu.hk:8000/evaluate
        - NEXT_PUBLIC_DEFAULT_STOCKS_URL=http://gan.cs.cityu.edu.hk:8000/default_stocks
    ports:
      - "80:3000"
    depends_on:
      - model_evaluation_platform_api
  model_evaluation_platform_api:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./model_evaluation_platform/api/Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --log-level debug
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=Model Evaluation Platform API
      - APP_DESCRIPTION=The API of the Model Evaluation Platform for project A Comparative Study of BGRU and GAN for Stock Market Forecasting in dual regions
      - APP_VERSION=1.0.0
      - PATH_PREFIX=/api/
      - HK_MODELS_CHECKPOINT_PATH=${PATH_PREFIX}model/hk
      - US_MODELS_CHECKPOINT_PATH=${PATH_PREFIX}model/us
      - EVALUATION_STOCKS_PATH=${PATH_PREFIX}data/processed/stocks_for_evaluate
      - SCALER_PATH=${PATH_PREFIX}scaler
      - RAW_DATA_PATH=${PATH_PREFIX}data/raw
      - FRONT_END_URL=http://gan.cs.cityu.edu.hk
      - API_TIMEOUT_MINUTES=3